# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_form.ui'
##
## Created by: Qt User Interface Compiler version 6.1.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore


class Ui_UI_GUI(object):
    def setupUi(self, UI_GUI):
        if not UI_GUI.objectName():
            UI_GUI.setObjectName(u"UI_GUI")
        UI_GUI.setEnabled(True)
        UI_GUI.resize(500, 500)
        UI_GUI.setMinimumSize(QSize(500, 500))
        UI_GUI.setMaximumSize(QSize(500, 500))
        self.pushButtonCancel = QPushButton(UI_GUI)
        self.pushButtonCancel.setObjectName(u"pushButtonCancel")
        self.pushButtonCancel.setGeometry(QRect(20, 450, 121, 32))
        self.groupBoxTIF2PNG = QGroupBox(UI_GUI)
        self.groupBoxTIF2PNG.setObjectName(u"groupBoxTIF2PNG")
        self.groupBoxTIF2PNG.setGeometry(QRect(10, 30, 481, 101))
        self.pushButtonRun = QPushButton(self.groupBoxTIF2PNG)
        self.pushButtonRun.setObjectName(u"pushButtonRun")
        self.pushButtonRun.setGeometry(QRect(390, 30, 81, 71))
        self.lineEditTIF = QLineEdit(self.groupBoxTIF2PNG)
        self.lineEditTIF.setObjectName(u"lineEditTIF")
        self.lineEditTIF.setGeometry(QRect(110, 30, 221, 21))
        self.lineEditPNG = QLineEdit(self.groupBoxTIF2PNG)
        self.lineEditPNG.setObjectName(u"lineEditPNG")
        self.lineEditPNG.setGeometry(QRect(110, 70, 221, 21))
        self.toolButtonPNG = QToolButton(self.groupBoxTIF2PNG)
        self.toolButtonPNG.setObjectName(u"toolButtonPNG")
        self.toolButtonPNG.setGeometry(QRect(350, 70, 26, 22))
        self.toolButtonTIF = QToolButton(self.groupBoxTIF2PNG)
        self.toolButtonTIF.setObjectName(u"toolButtonTIF")
        self.toolButtonTIF.setGeometry(QRect(350, 30, 26, 22))
        self.labelTIF = QLabel(self.groupBoxTIF2PNG)
        self.labelTIF.setObjectName(u"labelTIF")
        self.labelTIF.setGeometry(QRect(10, 30, 84, 16))
        self.labelPNG = QLabel(self.groupBoxTIF2PNG)
        self.labelPNG.setObjectName(u"labelPNG")
        self.labelPNG.setGeometry(QRect(10, 70, 75, 16))
        self.groupBoxResizePNG = QGroupBox(UI_GUI)
        self.groupBoxResizePNG.setObjectName(u"groupBoxResizePNG")
        self.groupBoxResizePNG.setGeometry(QRect(10, 140, 481, 141))
        self.pushButtonRun_Resize = QPushButton(self.groupBoxResizePNG)
        self.pushButtonRun_Resize.setObjectName(u"pushButtonRun_Resize")
        self.pushButtonRun_Resize.setGeometry(QRect(390, 30, 81, 71))
        self.lineEdit_InputPNG = QLineEdit(self.groupBoxResizePNG)
        self.lineEdit_InputPNG.setObjectName(u"lineEdit_InputPNG")
        self.lineEdit_InputPNG.setGeometry(QRect(110, 30, 221, 21))
        self.lineEdit_OutputPNG = QLineEdit(self.groupBoxResizePNG)
        self.lineEdit_OutputPNG.setObjectName(u"lineEdit_OutputPNG")
        self.lineEdit_OutputPNG.setGeometry(QRect(110, 70, 221, 21))
        self.toolButton_OutputPNG = QToolButton(self.groupBoxResizePNG)
        self.toolButton_OutputPNG.setObjectName(u"toolButton_OutputPNG")
        self.toolButton_OutputPNG.setGeometry(QRect(350, 70, 26, 22))
        self.toolButton_InputPNG = QToolButton(self.groupBoxResizePNG)
        self.toolButton_InputPNG.setObjectName(u"toolButton_InputPNG")
        self.toolButton_InputPNG.setGeometry(QRect(350, 30, 26, 22))
        self.label_InputPNG = QLabel(self.groupBoxResizePNG)
        self.label_InputPNG.setObjectName(u"label_InputPNG")
        self.label_InputPNG.setGeometry(QRect(10, 30, 84, 16))
        self.label_OutputPNG = QLabel(self.groupBoxResizePNG)
        self.label_OutputPNG.setObjectName(u"label_OutputPNG")
        self.label_OutputPNG.setGeometry(QRect(10, 70, 75, 16))
        self.horizontalSlider = QSlider(self.groupBoxResizePNG)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(110, 101, 221, 31))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(200)
        self.horizontalSlider.setSliderPosition(50)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(10)
        self.labelPNG_3 = QLabel(self.groupBoxResizePNG)
        self.labelPNG_3.setObjectName(u"labelPNG_3")
        self.labelPNG_3.setGeometry(QRect(10, 110, 71, 16))
        self.ScaleLabel = QLabel(self.groupBoxResizePNG)
        self.ScaleLabel.setObjectName(u"ScaleLabel")
        self.ScaleLabel.setGeometry(QRect(350, 110, 41, 16))
        self.Percentage = QLabel(self.groupBoxResizePNG)
        self.Percentage.setObjectName(u"Percentage")
        self.Percentage.setGeometry(QRect(390, 110, 41, 16))
        self.groupBox = QGroupBox(UI_GUI)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 290, 481, 101))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 71, 16))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 60, 81, 16))
        self.lineEdit_InputMask = QLineEdit(self.groupBox)
        self.lineEdit_InputMask.setObjectName(u"lineEdit_InputMask")
        self.lineEdit_InputMask.setGeometry(QRect(110, 30, 221, 21))
        self.lineEdit_OutputMask = QLineEdit(self.groupBox)
        self.lineEdit_OutputMask.setObjectName(u"lineEdit_OutputMask")
        self.lineEdit_OutputMask.setGeometry(QRect(110, 60, 221, 21))
        self.toolButton_InputMask = QToolButton(self.groupBox)
        self.toolButton_InputMask.setObjectName(u"toolButton_InputMask")
        self.toolButton_InputMask.setGeometry(QRect(350, 30, 26, 22))
        self.toolButton_OutputMask = QToolButton(self.groupBox)
        self.toolButton_OutputMask.setObjectName(u"toolButton_OutputMask")
        self.toolButton_OutputMask.setGeometry(QRect(350, 60, 26, 22))
        self.pushButtonRun_InvertMask = QPushButton(self.groupBox)
        self.pushButtonRun_InvertMask.setObjectName(u"pushButtonRun_InvertMask")
        self.pushButtonRun_InvertMask.setGeometry(QRect(390, 20, 81, 71))
#if QT_CONFIG(shortcut)
        self.labelTIF.setBuddy(self.labelTIF)
        self.label_InputPNG.setBuddy(self.labelTIF)
#endif // QT_CONFIG(shortcut)
        QWidget.setTabOrder(self.lineEditTIF, self.toolButtonTIF)
        QWidget.setTabOrder(self.toolButtonTIF, self.lineEditPNG)
        QWidget.setTabOrder(self.lineEditPNG, self.toolButtonPNG)
        QWidget.setTabOrder(self.toolButtonPNG, self.pushButtonRun)

        self.retranslateUi(UI_GUI)
        self.horizontalSlider.valueChanged.connect(self.ScaleLabel.setNum)

        QMetaObject.connectSlotsByName(UI_GUI)
    # setupUi

    def retranslateUi(self, UI_GUI):
        UI_GUI.setWindowTitle(QCoreApplication.translate("UI_GUI", u"Image Converter", None))
        self.pushButtonCancel.setText(QCoreApplication.translate("UI_GUI", u"Exit", None))
        self.groupBoxTIF2PNG.setTitle(QCoreApplication.translate("UI_GUI", u"TIF to PNG", None))
        self.pushButtonRun.setText(QCoreApplication.translate("UI_GUI", u"Convert", None))
        self.lineEditTIF.setPlaceholderText(QCoreApplication.translate("UI_GUI", u"*/*.tif", None))
        self.lineEditPNG.setPlaceholderText(QCoreApplication.translate("UI_GUI", u"*/*.png", None))
        self.toolButtonPNG.setText(QCoreApplication.translate("UI_GUI", u"...", None))
        self.toolButtonTIF.setText(QCoreApplication.translate("UI_GUI", u"...", None))
        self.labelTIF.setText(QCoreApplication.translate("UI_GUI", u"GeoTIF Image", None))
        self.labelPNG.setText(QCoreApplication.translate("UI_GUI", u"PNG Images", None))
        self.groupBoxResizePNG.setTitle(QCoreApplication.translate("UI_GUI", u"Resize PNG", None))
        self.pushButtonRun_Resize.setText(QCoreApplication.translate("UI_GUI", u"Resize", None))
        self.lineEdit_InputPNG.setPlaceholderText(QCoreApplication.translate("UI_GUI", u"*/*.png", None))
        self.lineEdit_OutputPNG.setPlaceholderText(QCoreApplication.translate("UI_GUI", u"*/*.png", None))
        self.toolButton_OutputPNG.setText(QCoreApplication.translate("UI_GUI", u"...", None))
        self.toolButton_InputPNG.setText(QCoreApplication.translate("UI_GUI", u"...", None))
        self.label_InputPNG.setText(QCoreApplication.translate("UI_GUI", u"Input PNG", None))
        self.label_OutputPNG.setText(QCoreApplication.translate("UI_GUI", u"Output PNG", None))
        self.labelPNG_3.setText(QCoreApplication.translate("UI_GUI", u"Scale", None))
        self.ScaleLabel.setText(QCoreApplication.translate("UI_GUI", u"50", None))
        self.Percentage.setText(QCoreApplication.translate("UI_GUI", u"%", None))
        self.groupBox.setTitle(QCoreApplication.translate("UI_GUI", u"Invert Mask PNG", None))
        self.label.setText(QCoreApplication.translate("UI_GUI", u"Input Mask", None))
        self.label_2.setText(QCoreApplication.translate("UI_GUI", u"Output Mask", None))
        self.lineEdit_InputMask.setPlaceholderText(QCoreApplication.translate("UI_GUI", u"*/*.png", None))
        self.lineEdit_OutputMask.setPlaceholderText(QCoreApplication.translate("UI_GUI", u"*/*.png", None))
        self.toolButton_InputMask.setText(QCoreApplication.translate("UI_GUI", u"...", None))
        self.toolButton_OutputMask.setText(QCoreApplication.translate("UI_GUI", u"...", None))
        self.pushButtonRun_InvertMask.setText(QCoreApplication.translate("UI_GUI", u"Invert", None))
    # retranslateUi

